import dotenv from 'dotenv'
dotenv.config()
export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>{children}</body>
    </html>
  )
}
