export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  console.log('haha happened')
  return (
    <html lang="en">

      <body>{children}</body>
    </html>
  )
}
